version: '3.8'

services:
  db:
    image: postgres:18
    container_name: taskflow-db
    environment:
      POSTGRES_DB: taskflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - taskflow-data:/var/lib/postgresql/data
    networks:
      - taskflow-net

  app:
    build: .
    container_name: taskflow-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskflow_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - taskflow-net

volumes:
  taskflow-data:

networks:
  taskflow-net:
    driver: bridge
